

  
    private FilteredEventType FILTEREDEVENTTYPE_CONSTRUCTFINISH;
    private FilteredEventType FILTEREDEVENTTYPE_CONSTRUCTSTART;
    private FilteredEventType FILTEREDEVENTTYPE_CONSTRUCTCANCEL;
  


    PlayerUnitEventAddFilteredAction(EVENT_PLAYER_UNIT_CONSTRUCT_FINISH, whichTriggerAction, FILTEREDEVENTTYPE_CONSTRUCTFINISH, CONSTRUCTId);
  }


    PlayerUnitEventAddFilteredAction(EVENT_PLAYER_UNIT_CONSTRUCT_START, whichTriggerAction, FILTEREDEVENTTYPE_CONSTRUCTSTART, CONSTRUCTId);
  }


    PlayerUnitEventAddFilteredAction(EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL, whichTriggerAction, FILTEREDEVENTTYPE_CONSTRUCTCANCEL, CONSTRUCTId);
  }


    PlayerUnitEventExecute(EVENT_PLAYER_UNIT_CONSTRUCT_FINISH, FILTEREDEVENTTYPE_CONSTRUCTFINISH, GetUnitTypeId(GetTriggerUnit()));
  }


    PlayerUnitEventExecute(EVENT_PLAYER_UNIT_CONSTRUCT_START, FILTEREDEVENTTYPE_CONSTRUCTSTART, GetUnitTypeId(GetTriggerUnit()));
  }


    PlayerUnitEventExecute(EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL, FILTEREDEVENTTYPE_CONSTRUCTCANCEL, GetUnitTypeId(GetTriggerUnit()));
  }

  private static void OnInit( ){



    FILTEREDEVENTTYPE_CONSTRUCTFINISH = FilteredEventType.create();
    FILTEREDEVENTTYPE_CONSTRUCTSTART = FilteredEventType.create();
    FILTEREDEVENTTYPE_CONSTRUCTCANCEL = FilteredEventType.create();
  }

}
