using System.Text;
using War3Api.Object;
using War3Net.Build;
using War3Net.Build.Environment;
using War3Net.CodeAnalysis.Jass.Extensions;
using War3Net.Common.Extensions;
using Warcraft.Cartographer.Extensions;

namespace Warcraft.Cartographer.Generation;

public sealed class ConstantsGenerator(ConstantsGeneratorOptions options)
{
  public void GenerateConstants(Map map)
  {
    var objectDatabase = map.GetObjectDatabaseFromMap();
    GenerateConstants(
      objectDatabase.GetUnits(),
      "Units",
      GetUnitPropertyName);

    GenerateConstants(
      objectDatabase.GetAbilities(),
      "Abilities",
      GetAbilityPropertyName);

    GenerateConstants(
      objectDatabase.GetBuffs(),
      "Buffs",
      GetBuffPropertyName);

    GenerateConstants(
      objectDatabase.GetItems(),
      "Items",
      GetItemPropertyName);

    GenerateConstants(
      objectDatabase.GetUpgrades(),
      "Upgrades",
      GetUpgradePropertyName);

    GenerateRegions(map.Regions!.Regions);
  }

  private void GenerateConstants<T>(
    IEnumerable<T> objects,
    string className,
    Func<T, string> getPropertyName) where T : BaseObject
  {
    using var writer = new StreamWriter(
      Path.Combine(options.ConstantsOutputPath, $"{className}.g.cs"),
      false,
      Encoding.UTF8);

    WriteHeader(writer, className);

    foreach (var obj in objects)
    {
      writer.WriteLine($"  public const int {Sanitize(getPropertyName(obj))} = {obj.GetId().InvertEndianness()};");
    }

    writer.WriteLine("}");
  }

  private void GenerateRegions(List<Region> regions)
  {
    using var writer = new StreamWriter(
      Path.Combine(options.RegionsOutputPath, "Regions.g.cs"),
      false,
      Encoding.UTF8);

    writer.WriteLine("using WCSharp.Shared.Data;");
    WriteHeader(writer, "Regions");

    foreach (var region in regions)
    {
      var propertyName = Sanitize(region.Name.Replace(" ", "_"));
      var propertyValue = string.Create(System.Globalization.CultureInfo.InvariantCulture,
        $"new Rectangle({region.Left}f, {region.Bottom}f, {region.Right}f, {region.Top}f)");
      writer.WriteLine($"  public static Rectangle {propertyName} {{ get; set; }} = {propertyValue};");
    }

    writer.WriteLine("}");
  }

  private static string GetUnitPropertyName(Unit unit) =>
    $"UNIT_{unit.Key.ToRawcode()}_{unit.TextName}_{unit.TextNameEditorSuffix}".ToUpper();

  private static string GetAbilityPropertyName(Ability ability) =>
    $"ABILITY_{ability.Key.ToRawcode()}_{ability.TextName}_{ability.TextEditorSuffix}".ToUpper();

  private static string GetBuffPropertyName(Buff buff)
  {
    var buffName = buff.IsTextNameEditorOnlyModified ? buff.TextNameEditorOnly : buff.TextTooltip;
    return $"BUFF_{buff.Key.ToRawcode()}_{buffName}_{buff.TextEditorSuffix}".ToUpper();
  }

  private static string GetItemPropertyName(Item item) =>
    $"ITEM_{item.Key.ToRawcode()}_{item.TextName}".ToUpper();

  private static string GetUpgradePropertyName(Upgrade upgrade)
  {
    var editorSuffix = upgrade.IsTextEditorSuffixModified[1] ? upgrade.TextEditorSuffix[1] : "";
    return
      $"UPGRADE_{upgrade.Key.ToRawcode()}_{upgrade.TextName[1]}_{editorSuffix}"
        .ToUpper();
  }

  private static string Sanitize(string input)
  {
    if (string.IsNullOrWhiteSpace(input))
    {
      return string.Empty;
    }

    var sb = new StringBuilder(input.Length);
    var lastWasSeparator = true; // prevents leading underscore

    foreach (var c in input)
    {
      if (char.IsLetterOrDigit(c))
      {
        sb.Append(c);
        lastWasSeparator = false;
      }
      else if (!lastWasSeparator)
      {
        sb.Append('_');
        lastWasSeparator = true;
      }
    }

    if (sb.Length > 0 && sb[^1] == '_')
    {
      sb.Length--;
    }

    return sb.ToString();
  }

  private static void WriteHeader(StreamWriter writer, string title)
  {
    writer.WriteLine("#pragma warning disable");
    writer.WriteLine("// This class is autogenerated by WarcraftLegacies.CLI.Services.ConstantsGenerator.");
    writer.WriteLine($"public static class {title}");
    writer.WriteLine("{");
  }
}
