<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <WarningLevel>0</WarningLevel>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <WarningLevel>0</WarningLevel>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="War3Net.Build" Version="6.0.3" />
        <PackageReference Include="War3Net.Build.Core" Version="6.0.3" />
        <PackageReference Include="War3Net.Common" Version="6.0.2" />
    </ItemGroup>

</Project>
