namespace Launcher.DataTransferObjects.War3Api.Object
{
  public sealed class UnitDto
    {
        public string ArtRequiredAnimationNamesRaw { get; set; }
        public string ArtIconGameInterfaceRaw { get; set; }
        public string ArtRequiredAnimationNamesAttachmentsRaw { get; set; }
        public string ArtRequiredAttachmentLinkNamesRaw { get; set; }
        public string TextTooltipAwaken { get; set; }
        public string ArtRequiredBoneNamesRaw { get; set; }
        public string SoundConstructionRaw { get; set; }
        public string TechtreeStructuresBuiltRaw { get; set; }
        public int ArtButtonPositionX { get; set; }
        public int ArtButtonPositionY { get; set; }
        public string ArtCasterUpgradeArtRaw { get; set; }
        public string TextCasterUpgradeNamesRaw { get; set; }
        public string TextCasterUpgradeTipsRaw { get; set; }
        public string TechtreeDependencyEquivalentsRaw { get; set; }
        public string TextDescription { get; set; }
        public string TextNameEditorSuffix { get; set; }
        public string TextHotkeyRaw { get; set; }
        public int SoundLoopingFadeInRate { get; set; }
        public int SoundLoopingFadeOutRate { get; set; }
        public string TechtreeItemsMadeRaw { get; set; }
        public float CombatAttack1ProjectileArc { get; set; }
        public float CombatAttack2ProjectileArc { get; set; }
        public string CombatAttack1ProjectileArtRaw { get; set; }
        public string CombatAttack2ProjectileArtRaw { get; set; }
        public int CombatAttack1ProjectileHomingEnabledRaw { get; set; }
        public int CombatAttack2ProjectileHomingEnabledRaw { get; set; }
        public int CombatAttack1ProjectileSpeed { get; set; }
        public int CombatAttack2ProjectileSpeed { get; set; }
        public string SoundMovementRaw { get; set; }
        public string TextName { get; set; }
        public string TextProperNamesRaw { get; set; }
        public string SoundRandomRaw { get; set; }
        public int TechtreeRequirementsTiersUsed { get; set; }
        public string TechtreeRequirementsRaw { get; set; }
        public string TechtreeRequirementsTier2Raw { get; set; }
        public string TechtreeRequirementsTier3Raw { get; set; }
        public string TechtreeRequirementsTier4Raw { get; set; }
        public string TechtreeRequirementsTier5Raw { get; set; }
        public string TechtreeRequirementsTier6Raw { get; set; }
        public string TechtreeRequirementsTier7Raw { get; set; }
        public string TechtreeRequirementsTier8Raw { get; set; }
        public string TechtreeRequirementsTier9Raw { get; set; }
        public string TechtreeRequirementsLevelsRaw { get; set; }
        public string TechtreeResearchesAvailableRaw { get; set; }
        public int TechtreeRevivesDeadHeroesRaw { get; set; }
        public string TextTooltipRevive { get; set; }
        public string ArtIconScoreScreenRaw { get; set; }
        public string TechtreeItemsSoldRaw { get; set; }
        public string TechtreeUnitsSoldRaw { get; set; }
        public string ArtSpecialRaw { get; set; }
        public string ArtTargetRaw { get; set; }
        public string TextTooltipBasic { get; set; }
        public string TechtreeUnitsTrainedRaw { get; set; }
        public string TechtreeHeroRevivalLocationsRaw { get; set; }
        public string TextTooltipExtended { get; set; }
        public string TechtreeUpgradesToRaw { get; set; }
        public string AbilitiesNormalRaw { get; set; }
        public string AbilitiesDefaultActiveAbilityRaw { get; set; }
        public string AbilitiesHeroRaw { get; set; }
        public int StatsStartingAgility { get; set; }
        public float StatsAgilityPerLevel { get; set; }
        public int StatsBuildTime { get; set; }
        public int StatsGoldBountyAwardedNumberOfDice { get; set; }
        public int StatsGoldBountyAwardedBase { get; set; }
        public int StatsGoldBountyAwardedSidesPerDie { get; set; }
        public int StatsLumberBountyAwardedNumberOfDice { get; set; }
        public int StatsLumberBountyAwardedBase { get; set; }
        public int StatsLumberBountyAwardedSidesPerDie { get; set; }
        public float PathingCollisionSize { get; set; }
        public int CombatDefenseBase { get; set; }
        public string CombatDefenseTypeRaw { get; set; }
        public int CombatDefenseUpgradeBonus { get; set; }
        public int StatsFoodProduced { get; set; }
        public int StatsFoodCost { get; set; }
        public int StatsGoldCost { get; set; }
        public int StatsRepairGoldCost { get; set; }
        public int StatsHitPointsMaximumBase { get; set; }
        public int StatsStartingIntelligence { get; set; }
        public float StatsIntelligencePerLevel { get; set; }
        public int StatsIsABuildingRaw { get; set; }
        public int StatsLevel { get; set; }
        public int StatsLumberCost { get; set; }
        public int StatsRepairLumberCost { get; set; }
        public int StatsManaInitialAmount { get; set; }
        public int StatsManaMaximum { get; set; }
        public int MovementSpeedMaximum { get; set; }
        public int MovementSpeedMinimum { get; set; }
        public int StatsNeutralBuildingValidAsRandomBuildingRaw { get; set; }
        public int StatsSightRadiusNight { get; set; }
        public string PathingPlacementRequiresRaw { get; set; }
        public string StatsPrimaryAttributeRaw { get; set; }
        public float StatsHitPointsRegenerationRate { get; set; }
        public float StatsManaRegeneration { get; set; }
        public string StatsHitPointsRegenerationTypeRaw { get; set; }
        public int StatsRepairTime { get; set; }
        public int MovementGroupSeparationEnabledRaw { get; set; }
        public int MovementGroupSeparationGroupNumber { get; set; }
        public int MovementGroupSeparationParameter { get; set; }
        public int MovementGroupSeparationPriority { get; set; }
        public string PathingPlacementPreventedByRaw { get; set; }
        public int StatsSightRadiusDay { get; set; }
        public int MovementSpeedBase { get; set; }
        public int StatsStockMaximum { get; set; }
        public int StatsStockReplenishInterval { get; set; }
        public int StatsStockStartDelay { get; set; }
        public int StatsStockInitialAfterStartDelay { get; set; }
        public int StatsStartingStrength { get; set; }
        public float StatsStrengthPerLevel { get; set; }
        public string EditorTilesetsRaw { get; set; }
        public string StatsUnitClassificationRaw { get; set; }
        public string TechtreeUpgradesUsedRaw { get; set; }
        public float PathingAIPlacementRadius { get; set; }
        public string PathingAIPlacementTypeRaw { get; set; }
        public int StatsCanBuildOnRaw { get; set; }
        public int StatsCanFleeRaw { get; set; }
        public int StatsSleepsRaw { get; set; }
        public int StatsTransportedSize { get; set; }
        public float ArtDeathTimeseconds { get; set; }
        public int CombatDeathTypeRaw { get; set; }
        public int ArtUseExtendedLineOfSightRaw { get; set; }
        public int StatsFormationRank { get; set; }
        public int StatsCanBeBuiltOnRaw { get; set; }
        public float MovementHeightMinimum { get; set; }
        public float MovementHeight { get; set; }
        public string MovementTypeRaw { get; set; }
        public int TextProperNamesUsed { get; set; }
        public int ArtOrientationInterpolation { get; set; }
        public string PathingPathingMapRaw { get; set; }
        public int StatsPointValue { get; set; }
        public int StatsPriority { get; set; }
        public float ArtPropulsionWindowdegrees { get; set; }
        public string StatsRaceRaw { get; set; }
        public float PathingPlacementRequiresWaterRadius { get; set; }
        public string CombatTargetedAsRaw { get; set; }
        public float MovementTurnRate { get; set; }
        public string CombatArmorTypeRaw { get; set; }
        public float ArtAnimationBlendTimeseconds { get; set; }
        public int ArtTintingColor3Blue { get; set; }
        public string ArtShadowTextureBuildingRaw { get; set; }
        public int EditorCategorizationCampaignRaw { get; set; }
        public int ArtAllowCustomTeamColorRaw { get; set; }
        public int EditorCanDropItemsOnDeathRaw { get; set; }
        public int ArtElevationSamplePoints { get; set; }
        public float ArtElevationSampleRadius { get; set; }
        public string ArtModelFileRaw { get; set; }
        public int ArtModelFileExtraVersionsRaw { get; set; }
        public float ArtFogOfWarSampleRadius { get; set; }
        public int ArtTintingColor2Green { get; set; }
        public int EditorDisplayAsNeutralHostileRaw { get; set; }
        public int EditorPlaceableInEditorRaw { get; set; }
        public float ArtMaximumPitchAngledegrees { get; set; }
        public float ArtMaximumRollAngledegrees { get; set; }
        public float ArtScalingValue { get; set; }
        public int StatsNeutralBuildingShowsMinimapIconRaw { get; set; }
        public int StatsHeroHideHeroInterfaceIconRaw { get; set; }
        public int StatsHeroHideHeroMinimapDisplayRaw { get; set; }
        public int StatsHeroHideHeroDeathMessageRaw { get; set; }
        public int StatsHideMinimapDisplayRaw { get; set; }
        public float ArtOccluderHeight { get; set; }
        public int ArtTintingColor1Red { get; set; }
        public float ArtAnimationRunSpeed { get; set; }
        public float ArtSelectionScale { get; set; }
        public int ArtScaleProjectilesRaw { get; set; }
        public int ArtSelectionCircleOnWaterRaw { get; set; }
        public float ArtSelectionCircleHeight { get; set; }
        public float ArtShadowImageHeight { get; set; }
        public int ArtHasWaterShadowRaw { get; set; }
        public float ArtShadowImageWidth { get; set; }
        public float ArtShadowImageCenterX { get; set; }
        public float ArtShadowImageCenterY { get; set; }
        public int EditorCategorizationSpecialRaw { get; set; }
        public int ArtTeamColorRaw { get; set; }
        public int EditorHasTilesetSpecificDataRaw { get; set; }
        public string ArtGroundTextureRaw { get; set; }
        public string ArtShadowImageUnitRaw { get; set; }
        public string SoundUnitSoundSetRaw { get; set; }
        public int EditorUseClickHelperRaw { get; set; }
        public float ArtAnimationWalkSpeed { get; set; }
        public float CombatAcquisitionRange { get; set; }
        public string CombatAttack1AttackTypeRaw { get; set; }
        public string CombatAttack2AttackTypeRaw { get; set; }
        public float CombatAttack1AnimationBackswingPoint { get; set; }
        public float CombatAttack2AnimationBackswingPoint { get; set; }
        public float ArtAnimationCastBackswing { get; set; }
        public float ArtAnimationCastPoint { get; set; }
        public float CombatAttack1CooldownTime { get; set; }
        public float CombatAttack2CooldownTime { get; set; }
        public float CombatAttack1DamageLossFactor { get; set; }
        public float CombatAttack2DamageLossFactor { get; set; }
        public int CombatAttack1DamageNumberOfDice { get; set; }
        public int CombatAttack2DamageNumberOfDice { get; set; }
        public int CombatAttack1DamageBase { get; set; }
        public int CombatAttack2DamageBase { get; set; }
        public float CombatAttack1AnimationDamagePoint { get; set; }
        public float CombatAttack2AnimationDamagePoint { get; set; }
        public int CombatAttack1DamageUpgradeAmount { get; set; }
        public int CombatAttack2DamageUpgradeAmount { get; set; }
        public int CombatAttack1AreaOfEffectFullDamage { get; set; }
        public int CombatAttack2AreaOfEffectFullDamage { get; set; }
        public int CombatAttack1AreaOfEffectMediumDamage { get; set; }
        public int CombatAttack2AreaOfEffectMediumDamage { get; set; }
        public float CombatAttack1DamageFactorMedium { get; set; }
        public float CombatAttack2DamageFactorMedium { get; set; }
        public float ArtProjectileImpactZSwimming { get; set; }
        public float ArtProjectileImpactZ { get; set; }
        public float ArtProjectileLaunchZSwimming { get; set; }
        public float ArtProjectileLaunchX { get; set; }
        public float ArtProjectileLaunchY { get; set; }
        public float ArtProjectileLaunchZ { get; set; }
        public int CombatMinimumAttackRange { get; set; }
        public int CombatAttack1AreaOfEffectSmallDamage { get; set; }
        public int CombatAttack2AreaOfEffectSmallDamage { get; set; }
        public float CombatAttack1DamageFactorSmall { get; set; }
        public float CombatAttack2DamageFactorSmall { get; set; }
        public int CombatAttack1Range { get; set; }
        public int CombatAttack2Range { get; set; }
        public float CombatAttack1RangeMotionBuffer { get; set; }
        public float CombatAttack2RangeMotionBuffer { get; set; }
        public int CombatAttack1ShowUIRaw { get; set; }
        public int CombatAttack2ShowUIRaw { get; set; }
        public int CombatAttack1DamageSidesPerDie { get; set; }
        public int CombatAttack2DamageSidesPerDie { get; set; }
        public float CombatAttack1DamageSpillDistance { get; set; }
        public float CombatAttack2DamageSpillDistance { get; set; }
        public float CombatAttack1DamageSpillRadius { get; set; }
        public float CombatAttack2DamageSpillRadius { get; set; }
        public string CombatAttack1AreaOfEffectTargetsRaw { get; set; }
        public string CombatAttack2AreaOfEffectTargetsRaw { get; set; }
        public int CombatAttack1MaximumNumberOfTargets { get; set; }
        public int CombatAttack2MaximumNumberOfTargets { get; set; }
        public string CombatAttack1TargetsAllowedRaw { get; set; }
        public string CombatAttack2TargetsAllowedRaw { get; set; }
        public int CombatAttacksEnabledRaw { get; set; }
        public string CombatAttack1WeaponTypeRaw { get; set; }
        public string CombatAttack2WeaponTypeRaw { get; set; }
        public string CombatAttack1WeaponSoundRaw { get; set; }
        public string CombatAttack2WeaponSoundRaw { get; set; }
        public string AbilitiesNormalSkinRaw { get; set; }
        public string AbilitiesHeroSkinRaw { get; set; }
    }
}